spring:
  application:
    name: vegankitchen
  threads:
    virtual:
      enabled: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
