INSERT INTO MENU_ITEM (NAME, DESCRIPTION, PRICE, CATEGORY, IMAGE_URL) VALUES
                                                                          ('Vegan Cheeseburger', 'Plant-based burger with vegan cheddar, lettuce, tomato, pickles and house sauce on a toasted bun.', 12.90, 'FOOD', 'https://images.unsplash.com/photo-1606755962773-d324e0a13086'),
                                                                          ('Falafel Wrap', 'Crispy chickpea falafel wrapped in pita with hummus, cucumber, tomato and tahini sauce.', 10.50, 'FOOD', 'https://images.unsplash.com/photo-1613145993481-6c1e06f6f8b1'),
                                                                          ('Quinoa Buddha Bowl', 'Quinoa bowl with roasted sweet potatoes, avocado, chickpeas, kale and lemon tahini dressing.', 13.20, 'FOOD', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd'),
                                                                          ('Vegan Margherita Pizza', 'Wood-fired pizza topped with tomato sauce, vegan mozzarella and fresh basil.', 14.00, 'FOOD', 'https://images.unsplash.com/photo-1594007654729-407eedc4be65'),
                                                                          ('Jackfruit Tacos', 'Three tacos filled with seasoned jackfruit, red cabbage slaw and avocado crema.', 11.80, 'FOOD', 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b'),
                                                                          ('Vegan Chocolate Cake', 'Rich dark chocolate cake layered with dairy-free chocolate ganache.', 6.50, 'DESSERT', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587'),
                                                                          ('Avocado Toast', 'Sourdough toast topped with smashed avocado, cherry tomatoes, chili flakes and olive oil.', 8.90, 'FOOD', 'https://images.unsplash.com/photo-1603048297172-c92544798d5a'),
                                                                          ('Green Detox Smoothie', 'Refreshing smoothie with spinach, banana, pineapple, ginger and coconut water.', 6.90, 'BEVERAGE', 'https://images.unsplash.com/photo-1553530666-ba11a7da3888'),
                                                                          ('Iced Oat Milk Latte', 'Cold brewed espresso served with creamy oat milk over ice.', 4.80, 'BEVERAGE', 'https://images.unsplash.com/photo-1517701604599-bb29b565090c'),
                                                                          ('Hibiscus Iced Tea', 'House-brewed hibiscus tea served chilled with lemon and agave syrup.', 3.90, 'BEVERAGE', 'https://images.unsplash.com/photo-1556679343-c7306c1976bc');